server:
  port: 8080
  servlet:
    context-path: /generate-file
spring:
  application:
    name: generate-file
  datasource:
    url: jdbc:mysql://localhost:3306/job_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&
    username: root
    password: root
#    url: jdbc:mysql://10.4.8.2:20059/job_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&
#    username: admin
#    password: Yixin@kkc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      database: 2
      host: 127.0.0.1
      port: 6379
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      joda-date-time-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null
  freemarker:
    check-template-location: false

logging:
  file: application.log
  path: .
  level:
    root: info
    com.lifengdi.store.client: DEBUG

file:
  localTempPath: /Users/goddess/
  appTempFolder: file/

# 腾讯云配置文件
cloud:
  secret.id: secret.id
  secret.key: secret.key
  app.id: 123456789
  bucket.name: bucket.name
  region: region
  cdn.dir.path: file_sys/yyyy/MM/
  cdn.url: cdn.url

# 生成PDF文件配置
pdf:
  pdfType:
    test:
      pdfTempFile:
        pdfType: test
        templateFileName: test.ftl
        templateFileParentPath: file/
      pdfStamperConfig:
        generate: true
        stamperUrl: image/666.png
        xOffset: 0
        yOffset: 45
        fitWidth: 120
        fitHeight: 120
        location:
          x: -1
          y: -1
          page: 1
          word: 检测日期
      pdfWatermarkConfig:
        generate: true
        watermarkWord: 水印
        watermarkColor:
        fillOpacity:
        fontSize:
        fontFamily: SourceHanSansCN
        location:
          xInterval: 100
          yInterval: 120
          page:
          overContent: true

success:
  successCode:
    200: 200
    2000: 2000

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: pageNum=page;pageSize=size;count=countSql;

mybatis:
  typeAliasesPackage: com.lifengdi.job.entity
  # mapper 的xml文件扫描路径
  mapper-locations: classpath:mapper/**/*.xml
